
spring:
  application:
    name: library-notifications-service
  cloud:
    stream:
      bindings:
        on-user-registration-notification-in-0:
          destination: user-registration-notification
          group: notification-service-group
          content-type: application/json
        on-borrowed-book-notification-in-0:
          destination: book-notification
          group: notification-service-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            auto.offset.reset: earliest
server:
  port: 9090